import { AlertTriangle, CheckCircle2, Sparkles, WalletCards } from 'lucide-react'

function score(value) { return value == null || Number.isNaN(Number(value)) ? '—' : Number(value).toFixed(1) }
function formatMoney(value) { return value == null ? '—' : `₹${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 0 })}` }

export default function AIAnalysisCard({ result, loading, error, onAnalyze }) {
  if (!result && !loading && !error) return <div className="soft-card p-5 sm:p-6"><div className="flex items-center gap-2 text-sm font-semibold text-neutral-900"><Sparkles size={17} /> UdyamSetu AI Analysis</div><p className="mt-2 text-xs leading-5 text-neutral-500">Use the calculator inputs to get a business fit assessment from the ML decision engine.</p><button type="button" onClick={onAnalyze} className="green-button mt-5 w-full">Analyze with UdyamSetu AI</button></div>
  const components = result?.scores?.components || {}
  const funding = result?.funding || {}
  const bestScheme = funding.schemes?.[0]
  const bestLoan = funding.loans?.[0]
  return <div className="soft-card p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-semibold text-neutral-900"><Sparkles size={17} /> UdyamSetu AI Analysis</div><div className="mt-1 text-xs text-neutral-500">Financial, market, operational, risk and ASUSE signals are combined into one practical assessment.</div></div>{result?.decision?.decision && <div className="rounded-full bg-udyam-50 px-3 py-1 text-xs font-semibold text-udyam-700">{result.decision.decision}</div>}</div>
    {loading && <div className="mt-5 text-xs text-neutral-500">Analyzing your business profile…</div>}{error && <div role="alert" className="mt-5 rounded-xl border border-red-100 bg-red-50 p-3 text-xs text-red-700">{error}</div>}
    {result && <><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{Object.entries(components).map(([key, value]) => <div key={key} className="rounded-xl border border-neutral-100 bg-neutral-50 p-3"><div className="text-[10px] uppercase tracking-wide text-neutral-500">{key.replaceAll('_', ' ')}</div><div className="mt-1 text-lg font-semibold text-neutral-900">{score(value)}</div></div>)}</div>
      <div className="mt-4 rounded-xl bg-[#f2f7ee] p-4"><div className="text-xs font-semibold text-neutral-900">Overall score: {score(result.decision?.overall_score)}/100</div><div className="mt-2 text-xs text-neutral-600">Confidence: {result.decision?.confidence == null ? '—' : `${(Number(result.decision.confidence) * 100).toFixed(0)}%`} · data quality</div></div>
      {(bestScheme || bestLoan) && <div className="mt-4 grid gap-3 sm:grid-cols-2">{bestScheme && <div className="rounded-xl border border-udyam-100 bg-udyam-50/50 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-neutral-900"><WalletCards size={15} /> Best scheme</div><div className="mt-2 text-sm font-semibold text-udyam-700">{bestScheme.scheme_name}</div><div className="mt-1 text-xs text-neutral-600">Up to {formatMoney(bestScheme.max_loan_amount)} · {bestScheme.interest_rate}% interest</div></div>}{bestLoan && <div className="rounded-xl border border-neutral-100 p-4"><div className="text-xs font-semibold text-neutral-900">Best loan plan</div><div className="mt-2 text-sm font-semibold text-udyam-700">{bestLoan.plan_name}</div><div className="mt-1 text-xs text-neutral-600">{bestLoan.bank_or_institution_name} · {bestLoan.interest_rate_min ?? '—'}–{bestLoan.interest_rate_max ?? '—'}%</div></div>}</div>}
      {(result.strengths?.length > 0 || result.concerns?.length > 0) && <div className="mt-4 grid gap-3 sm:grid-cols-2">{result.strengths?.length > 0 && <div className="rounded-xl border border-neutral-100 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-neutral-900"><CheckCircle2 size={15} /> Strengths</div><ul className="mt-2 grid gap-1 text-xs text-neutral-600">{result.strengths.map((x, i) => <li key={i}>• {x}</li>)}</ul></div>}{result.concerns?.length > 0 && <div className="rounded-xl border border-neutral-100 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-neutral-900"><AlertTriangle size={15} /> Concerns</div><ul className="mt-2 grid gap-1 text-xs text-neutral-600">{result.concerns.map((x, i) => <li key={i}>• {x}</li>)}</ul></div>}</div>}</>}
    <button type="button" onClick={onAnalyze} disabled={loading} className="green-button mt-5 w-full disabled:cursor-not-allowed disabled:opacity-60">{loading ? 'Analyzing…' : 'Refresh AI analysis'}</button>
  </div>
}
