import { CalendarDays, Percent, IndianRupee, Clock3, TrendingUp, CheckCircle, ExternalLink, Building2 } from 'lucide-react'
import { useLanguage } from '../../context/LanguageContext'

const money = (value) => value == null ? '—' : `₹${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`
const months = (value) => value == null ? '—' : `${value} months`

export default function SchemeCard({ item, type = 'scheme', matchScore }) {
  const { t } = useLanguage()
  const scheme = type === 'scheme'
  const title = scheme ? item.scheme_name : item.plan_name
  const summary = scheme ? item.description : item.key_features?.join?.(' • ') || item.geographic_focus || 'Funding option stored in the UdyamSetu database.'
  const interest = scheme ? `${item.interest_rate}%` : `${item.interest_rate_min ?? '—'}${item.interest_rate_max != null ? `–${item.interest_rate_max}` : ''}%`
  const tenure = scheme ? months(item.tenure_months) : item.tenure_min_months != null ? `${item.tenure_min_months}–${item.tenure_max_months ?? item.tenure_min_months} months` : '—'
  const loan = scheme ? money(item.max_loan_amount) : `${money(item.min_loan_amount)} – ${money(item.max_loan_amount)}`
  const reasons = Array.isArray(item.match_reasons) ? item.match_reasons.slice(0, 2) : []
  const applyUrl = scheme ? item.official_portal_url : item.source_url
  return <div className="soft-card rounded-[24px] border border-udyam-200 p-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-udyam-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-udyam-700">{scheme ? 'Scheme' : 'Loan plan'}</span>{item.scheme_code && <span className="text-[10px] font-semibold uppercase tracking-wide text-neutral-400">{item.scheme_code}</span>}</div><div className="mt-3 text-base font-bold text-udyam-700">{title || 'Unnamed funding option'}</div><div className="mt-1 text-xs leading-5 text-neutral-500">{summary}</div></div>{matchScore != null && <div className="flex shrink-0 items-center gap-2 rounded-full border border-udyam-200 bg-udyam-50 px-3 py-2"><TrendingUp size={15} className="text-udyam-700" /><span className="text-sm font-bold text-udyam-700">{Number(matchScore).toFixed(0)}%</span></div>}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-xl bg-[#f7faf4] p-4"><IndianRupee size={17} className="text-udyam-700" /><div className="mt-2 text-[11px] text-neutral-500">Loan / support limit</div><div className="mt-1 text-sm font-semibold">{loan}</div></div><div className="rounded-xl bg-[#f7faf4] p-4"><Percent size={17} className="text-udyam-700" /><div className="mt-2 text-[11px] text-neutral-500">Interest rate</div><div className="mt-1 text-sm font-semibold">{interest}</div><div className="mt-1 text-[10px] text-neutral-500">per annum</div></div><div className="rounded-xl bg-[#f7faf4] p-4"><CalendarDays size={17} className="text-udyam-700" /><div className="mt-2 text-[11px] text-neutral-500">Repayment tenure</div><div className="mt-1 text-sm font-semibold">{tenure}</div></div><div className="rounded-xl bg-[#f7faf4] p-4"><Clock3 size={17} className="text-udyam-700" /><div className="mt-2 text-[11px] text-neutral-500">Moratorium</div><div className="mt-1 text-sm font-semibold">{months(item.moratorium_months)}</div></div></div>
    <div className="mt-5 grid gap-5 border-t border-neutral-100 pt-5 md:grid-cols-2"><div><div className="flex items-center gap-2 text-xs font-semibold text-neutral-900"><Building2 size={14} /> {scheme ? 'Funding structure' : item.bank_or_institution_name || 'Institution'}</div><p className="mt-2 text-xs leading-5 text-neutral-600">{scheme ? `Funding ratio: ${item.funding_ratio ?? '—'} • Margin ratio: ${item.margin_ratio ?? '—'} • Maximum loan: ${money(item.max_loan_amount)}.` : `${item.institution_type || 'Institution'}${item.geographic_scope ? ` • ${item.geographic_scope}` : ''}${item.collateral_required ? ' • Collateral may be required.' : ' • No collateral flag stored.'}`}</p></div><div><div className="text-xs font-semibold text-neutral-900">Why it matches</div><ul className="mt-2 grid gap-1 text-xs leading-5 text-neutral-600">{(reasons.length ? reasons : ['Matched using the fields currently stored in the funding database.']).map((reason, index) => <li key={index}>• {reason}</li>)}</ul></div></div>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-neutral-100 pt-4"><span className="inline-flex items-center gap-2 text-[11px] font-bold uppercase tracking-wide text-udyam-700"><CheckCircle size={14} /> Best match</span>{applyUrl ? <a href={applyUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-udyam-700 px-4 py-2 text-xs font-bold text-white transition hover:bg-udyam-600">View source <ExternalLink size={14} /></a> : <span className="text-[11px] text-neutral-500">Source link not available</span>}</div>
  </div>
}
