"""Seed UdyamSetu reference data into PostgreSQL.

Populates the tables that can safely have reference/demo data before real users exist:
  - business_reference_profiles (40 researched profiles)
  - location_reference (curated Indian location centroids)
  - location_business_metrics (development baseline metrics for Business Insights)

The location-business metrics generated by this script are explicitly labelled as
DEVELOPMENT SEED data. They are not presented as observed market statistics. Replace
or overwrite them with validated market data before using them as real-world claims.

Tables intentionally NOT seeded:
  - user_locations: populated by live user location capture
  - business_analyses and child analysis tables: populated by real analyses
  - conversations/messages: populated by chatbot use

Usage (PowerShell):
  python database/seed_reference_data.py --dry-run
  python database/seed_reference_data.py

Requires DATABASE_URL in .env or environment.
"""
from __future__ import annotations

import argparse
import csv
import os
import uuid

from pathlib import Path
from typing import Any

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover
    load_dotenv = None

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PROFILE_CSV = ROOT / "seed_data" / "business_reference_profiles_database_ready.csv"
DEMO_METRICS_SOURCE = "UdyamSetu development seed"
PROFILE_SOURCE = "KVIC/PMEGP/MSME official project profile"
MAX_DB_VARCHAR = 200

def fit_text(value: Any, max_length: int = MAX_DB_VARCHAR) -> str | None:
    """Safely fit optional text into the database VARCHAR limit.

    The DB team may have VARCHAR(200) even if a newer reference schema uses TEXT.
    This keeps the seed portable across both versions without changing the schema.
    """
    if value is None:
        return None
    text = str(value).strip()
    return text[:max_length] if text else None

NAMESPACE = uuid.UUID("4f75b0b0-54b6-4d0e-b7cc-4a7a5a0b7c21")

# Curated city/district centroids used only to make the local development flow
# usable. These are location reference points, not precise user addresses.
LOCATIONS = [
    ("Delhi", "Delhi", "Central Delhi", 28.6139, 77.2090),
    ("Mumbai", "Maharashtra", "Mumbai City", 19.0760, 72.8777),
    ("Pune", "Maharashtra", "Pune", 18.5204, 73.8567),
    ("Ahmedabad", "Gujarat", "Ahmedabad", 23.0225, 72.5714),
    ("Surat", "Gujarat", "Surat", 21.1702, 72.8311),
    ("Jaipur", "Rajasthan", "Jaipur", 26.9124, 75.7873),
    ("Lucknow", "Uttar Pradesh", "Lucknow", 26.8467, 80.9462),
    ("Prayagraj", "Uttar Pradesh", "Prayagraj", 25.4358, 81.8463),
    ("Kanpur", "Uttar Pradesh", "Kanpur Nagar", 26.4499, 80.3319),
    ("Varanasi", "Uttar Pradesh", "Varanasi", 25.3176, 82.9739),
    ("Kolkata", "West Bengal", "Kolkata", 22.5726, 88.3639),
    ("Bengaluru", "Karnataka", "Bengaluru Urban", 12.9716, 77.5946),
    ("Hyderabad", "Telangana", "Hyderabad", 17.3850, 78.4867),
    ("Chennai", "Tamil Nadu", "Chennai", 13.0827, 80.2707),
    ("Kochi", "Kerala", "Ernakulam", 9.9312, 76.2673),
    ("Bhubaneswar", "Odisha", "Khordha", 20.2961, 85.8245),
    ("Patna", "Bihar", "Patna", 25.5941, 85.1376),
    ("Ranchi", "Jharkhand", "Ranchi", 23.3441, 85.3096),
    ("Indore", "Madhya Pradesh", "Indore", 22.7196, 75.8577),
    ("Guwahati", "Assam", "Kamrup Metropolitan", 26.1445, 91.7362),
]


def stable_uuid(*parts: Any) -> str:
    return str(uuid.uuid5(NAMESPACE, "|".join(str(p).strip().lower() for p in parts)))


def parse_jsonish(value: str | None) -> Any:
    if value is None or not str(value).strip():
        return {}
    text = str(value).strip()
    # Existing seed CSV stores resource/infrastructure/risk fields as semicolon-separated
    # text. Keep them as JSON arrays so JSONB remains structured.
    return [x.strip() for x in text.split(";") if x.strip()]


def num(value: str | None) -> float | None:
    if value is None or str(value).strip() == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def load_profiles(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No profiles found in {path}")
    required = {"business_name", "category", "subcategory"}
    missing = required - set(rows[0])
    if missing:
        raise ValueError(f"Profile CSV is missing columns: {sorted(missing)}")
    out = []
    for row in rows:
        original_id = row.get("profile_id") or row["business_name"]
        out.append({
            "profile_id": stable_uuid("profile", original_id),
            "business_name": fit_text(row["business_name"]),
            "category": fit_text(row.get("category"), 100),
            "subcategory": fit_text(row.get("subcategory"), 100),
            "minimum_capital": num(row.get("minimum_capital")),
            "typical_project_cost": num(row.get("typical_project_cost")),
            "expected_monthly_revenue": num(row.get("expected_monthly_revenue")),
            "expected_monthly_expenses": num(row.get("expected_monthly_expenses")),
            "expected_profit_margin": num(row.get("expected_profit_margin")),
            "typical_break_even_months": int(float(row["typical_break_even_months"])) if num(row.get("typical_break_even_months")) is not None else None,
            "resource_requirements": parse_jsonish(row.get("resource_requirements")),
            "infrastructure_requirements": parse_jsonish(row.get("infrastructure_requirements")),
            "risk_factors": parse_jsonish(row.get("risk_factors")),
            "data_source": PROFILE_SOURCE,
        })
    return out


def location_rows(location_id_type: str = "uuid") -> list[dict[str, Any]]:
    rows = []
    for idx, (name, state, district, lat, lon) in enumerate(LOCATIONS, start=1):
        if location_id_type in {"int2", "int4", "int8"}:
            location_id = idx
        else:
            location_id = stable_uuid("location", name, state, district)
        rows.append({
            "location_id": location_id,
            "location_name": name,
            "state": state,
            "district": district,
            "latitude": lat,
            "longitude": lon,
        })
    return rows


def get_column_udt(cur, table: str, column: str) -> str:
    cur.execute(
        "SELECT udt_name FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = %s AND column_name = %s",
        (table, column),
    )
    row = cur.fetchone()
    if not row:
        raise RuntimeError(f"Column {table}.{column} was not found in the connected database")
    return str(row[0])


def category_base(category: str | None) -> float:
    # Development-only priors. They deliberately do not claim to be observed demand.
    text = (category or "").lower()
    if any(k in text for k in ("food", "retail", "service")):
        return 62.0
    if any(k in text for k in ("manufact", "processing", "engineering")):
        return 56.0
    if any(k in text for k in ("agri", "dairy", "rural")):
        return 54.0
    return 50.0


def build_demo_metrics(profiles: list[dict[str, Any]], locations: list[dict[str, Any]]) -> list[tuple[Any, ...]]:
    # The city multiplier is only a development baseline to exercise the location-aware
    # Business Insights flow. Every row is labelled with DEMO_METRICS_SOURCE.
    city_multiplier = {
        "Delhi": 1.08, "Mumbai": 1.10, "Pune": 1.05, "Ahmedabad": 1.04,
        "Surat": 1.03, "Jaipur": 1.00, "Lucknow": 1.00, "Prayagraj": 0.94,
        "Kanpur": 0.96, "Varanasi": 0.98, "Kolkata": 1.03, "Bengaluru": 1.10,
        "Hyderabad": 1.06, "Chennai": 1.06, "Kochi": 1.02, "Bhubaneswar": 0.97,
        "Patna": 0.95, "Ranchi": 0.94, "Indore": 1.01, "Guwahati": 0.96,
    }
    rows = []
    for loc in locations:
        mult = city_multiplier.get(loc["location_name"], 1.0)
        for p in profiles:
            base = category_base(p["category"])
            demand = max(1.0, min(100.0, base * mult))
            competition = max(1.0, min(100.0, 42.0 + (mult - 0.94) * 90.0))
            competition_count = int(round(25 + competition * 1.8))
            opportunity = max(1.0, min(100.0, 0.65 * demand + 0.35 * (100.0 - competition)))
            avg_price = None  # No fabricated market price; keep it unavailable until sourced.
            rows.append((
                stable_uuid("metric", loc["location_id"], p["category"], p["subcategory"]),
                loc["location_id"], p["category"], p["subcategory"],
                round(demand, 3), competition_count, round(competition, 3),
                avg_price, round(opportunity, 3), fit_text(DEMO_METRICS_SOURCE), "2026-09-10",
            ))
    return rows


def seed(conn, profiles: list[dict[str, Any]], locations: list[dict[str, Any]], replace_demo_metrics: bool) -> dict[str, int]:
    from psycopg2.extras import Json, execute_values
    metrics = build_demo_metrics(profiles, locations)
    with conn.cursor() as cur:
        metric_location_type = get_column_udt(cur, "location_business_metrics", "location_id")
        reference_location_type = get_column_udt(cur, "location_reference", "location_id")
        if metric_location_type != reference_location_type:
            raise RuntimeError(
                "location_id type mismatch: location_business_metrics.location_id is "
                f"{metric_location_type}, but location_reference.location_id is {reference_location_type}. "
                "These two columns must have the same type because the ML location resolver uses the same location_id. "
                "Align the database columns before seeding."
            )
        if metric_location_type not in {"uuid", "int2", "int4", "int8"}:
            raise RuntimeError(
                f"Unsupported location_id PostgreSQL type: {metric_location_type}. "
                "Expected uuid or integer."
            )
        profile_sql = """
            INSERT INTO business_reference_profiles
            (profile_id, business_name, category, subcategory, minimum_capital,
             typical_project_cost, expected_monthly_revenue, expected_monthly_expenses,
             expected_profit_margin, typical_break_even_months, resource_requirements,
             infrastructure_requirements, risk_factors, data_source)
            VALUES %s
            ON CONFLICT DO NOTHING
        """
        profile_values = [
            (p["profile_id"], p["business_name"], p["category"], p["subcategory"],
             p["minimum_capital"], p["typical_project_cost"], p["expected_monthly_revenue"],
             p["expected_monthly_expenses"], p["expected_profit_margin"],
             p["typical_break_even_months"], Json(p["resource_requirements"]),
             Json(p["infrastructure_requirements"]), Json(p["risk_factors"]), p["data_source"])
            for p in profiles
        ]
        execute_values(cur, profile_sql, profile_values)

        location_sql = """
            INSERT INTO location_reference
            (location_id, location_name, state, district, latitude, longitude)
            VALUES %s
            ON CONFLICT DO NOTHING
        """
        location_values = [
            (l["location_id"], l["location_name"], l["state"], l["district"], l["latitude"], l["longitude"])
            for l in locations
        ]
        execute_values(cur, location_sql, location_values)

        if replace_demo_metrics:
            cur.execute("DELETE FROM location_business_metrics WHERE data_source = %s", (DEMO_METRICS_SOURCE,))

        metric_sql = """
            INSERT INTO location_business_metrics
            (metric_id, location_id, business_category, subcategory, demand_score,
             competition_count, competition_score, average_market_price, opportunity_score,
             data_source, data_date)
            VALUES %s
            ON CONFLICT DO NOTHING
        """
        execute_values(cur, metric_sql, metrics)
        conn.commit()
    return {"profiles": len(profiles), "locations": len(locations), "metrics": len(metrics)}


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed UdyamSetu ML reference tables")
    parser.add_argument("--profiles-csv", type=Path, default=DEFAULT_PROFILE_CSV)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--replace-demo-metrics", action="store_true", help="Replace prior development-seed metric rows")
    args = parser.parse_args()

    if load_dotenv:
        load_dotenv(ROOT / ".env")

    profiles = load_profiles(args.profiles_csv)
    locations = location_rows()

    metrics = build_demo_metrics(profiles, locations)
    print(f"Profiles prepared: {len(profiles)}")
    print(f"Locations prepared: {len(locations)}")
    print(f"Location metrics prepared: {len(metrics)}")
    print("Metric source: DEVELOPMENT SEED (replace with validated market data)")

    if args.dry_run:
        print("Dry run complete; database was not modified.")
        return

    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise SystemExit("DATABASE_URL is not set. Put the PostgreSQL/Supabase Session Pooler URL in backend/.env or the environment.")

    import psycopg2
    conn = psycopg2.connect(database_url)
    try:
        with conn.cursor() as cur:
            metric_location_type = get_column_udt(cur, "location_business_metrics", "location_id")
            reference_location_type = get_column_udt(cur, "location_reference", "location_id")
        if metric_location_type != reference_location_type:
            raise SystemExit(
                "Database location_id types do not match: "
                f"location_business_metrics={metric_location_type}, location_reference={reference_location_type}. "
                "Make both columns the same type before running the seed."
            )
        locations = location_rows(metric_location_type)
        result = seed(conn, profiles, locations, args.replace_demo_metrics)
        print(f"Inserted/updated: {result}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
