import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export const languages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'Hindi' },
  { code: 'bn', label: 'Bengali' },
  { code: 'mr', label: 'Marathi' },
  { code: 'ta', label: 'Tamil' },
  { code: 'te', label: 'Telugu' },
  { code: 'kn', label: 'Kannada' },
  { code: 'gu', label: 'Gujarati' },
  { code: 'pa', label: 'Punjabi' },
  { code: 'ml', label: 'Malayalam' },
  { code: 'or', label: 'Odia' },
]

const translations = {
  en: {
    nav: { home: 'Home', how: 'How it works', schemes: 'Schemes', insights: 'Business Insights', calculator: 'Calculator', assistant: 'AI Assistant', getStarted: 'Get Started', language: 'Language' },
    home: { kicker: 'AI Powered Business Advisory for Rural India', titleLead: 'Your', titleHighlight: 'Right Business Saathi', description: 'Start the right business with the right guidance. Get hyper-local market insights, financial planning, and government scheme guidance — all in one place.', start: 'Start your Business Journey', how: 'See How It Works', local: 'Local insight', demand: 'Dairy demand • High', explore: 'Explore UdyamSetu', exploreAction: 'Explore', insightsTitle: 'Business Insights', insightsText: 'Explore hyper-local market conditions', calculatorTitle: 'Smart Calculator', calculatorText: 'Estimate your project and loan structure', assistantTitle: 'AI Assistant', assistantText: 'Ask questions in simple language', schemesTitle: 'Government Schemes', schemesText: 'Compare scheme rules and limits' },
    onboarding: { kicker: 'Start your business journey', title: "Let's understand your idea", description: "Answer three simple questions. We'll prepare an indicative financial structure and local opportunity view.", location: 'Your location', business: 'Your business', margin: 'Your margin', where: 'Where will you start?', locationText: 'We use this to estimate the nearby market. You can refine it later.', what: 'What would you like to build?', businessText: 'Choose the closest category. You can discuss a more specific idea with the assistant later.', howMuch: 'How much margin money is available?', marginText: 'This is your indicative own contribution, not a promise of loan approval.', state: 'State', district: 'District', block: 'Block / area', category: 'Business category', available: 'Available margin money (₹)', back: 'Back', continue: 'Continue', seeStructure: 'See my structure', marginNote: "We'll use the stated 10% margin structure, then apply scheme caps and show the difference clearly." },
  },
  hi: {
    nav: { home: 'होम', how: 'यह कैसे काम करता है', schemes: 'योजनाएं', insights: 'व्यवसाय जानकारी', calculator: 'कैलकुलेटर', assistant: 'AI सहायक', getStarted: 'शुरू करें', language: 'भाषा' },
    home: { kicker: 'ग्रामीण भारत के लिए AI बिज़नेस सलाह', titleLead: 'आपका', titleHighlight: 'सही बिज़नेस साथी', description: 'सही मार्गदर्शन के साथ सही व्यवसाय शुरू करें। स्थानीय बाजार, वित्तीय योजना और सरकारी योजनाओं की जानकारी एक ही जगह पाएं।', start: 'बिज़नेस यात्रा शुरू करें', how: 'यह कैसे काम करता है', local: 'स्थानीय जानकारी', demand: 'डेयरी मांग • अधिक', explore: 'UdyamSetu देखें', exploreAction: 'देखें', insightsTitle: 'व्यवसाय जानकारी', insightsText: 'अपने स्थानीय बाजार को समझें', calculatorTitle: 'स्मार्ट कैलकुलेटर', calculatorText: 'परियोजना और ऋण संरचना का अनुमान लगाएं', assistantTitle: 'AI सहायक', assistantText: 'सरल भाषा में सवाल पूछें', schemesTitle: 'सरकारी योजनाएं', schemesText: 'योजना के नियम और सीमाएं देखें' },
    onboarding: { kicker: 'अपनी बिज़नेस यात्रा शुरू करें', title: 'आपके विचार को समझते हैं', description: 'तीन आसान सवालों के जवाब दें। हम वित्तीय ढांचा और स्थानीय अवसर की जानकारी तैयार करेंगे।', location: 'आपका स्थान', business: 'आपका व्यवसाय', margin: 'आपकी पूंजी', where: 'आप कहां शुरू करेंगे?', locationText: 'नजदीकी बाजार का अनुमान लगाने के लिए यह जानकारी उपयोग होगी।', what: 'आप क्या शुरू करना चाहते हैं?', businessText: 'सबसे सही श्रेणी चुनें। आप सहायक से अधिक जानकारी पूछ सकते हैं।', howMuch: 'आपके पास कितनी मार्जिन राशि है?', marginText: 'यह आपकी अनुमानित अपनी पूंजी है, ऋण मंजूरी का वादा नहीं।', state: 'राज्य', district: 'जिला', block: 'ब्लॉक / क्षेत्र', category: 'व्यवसाय श्रेणी', available: 'उपलब्ध मार्जिन राशि (₹)', back: 'वापस', continue: 'आगे बढ़ें', seeStructure: 'अपना ढांचा देखें', marginNote: 'हम 10% मार्जिन संरचना और योजना की सीमाओं के आधार पर अंतर स्पष्ट दिखाएंगे।' },
  },
  bn: { nav: { home: 'হোম', how: 'কীভাবে কাজ করে', schemes: 'প্রকল্প', insights: 'ব্যবসার তথ্য', calculator: 'ক্যালকুলেটর', assistant: 'AI সহায়ক', getStarted: 'শুরু করুন', language: 'ভাষা' }, home: { kicker: 'গ্রামীণ ভারতের জন্য AI ব্যবসায়িক পরামর্শ', titleLead: 'আপনার', titleHighlight: 'সঠিক ব্যবসার সাথী', description: 'সঠিক দিকনির্দেশনা নিয়ে সঠিক ব্যবসা শুরু করুন। স্থানীয় বাজার, আর্থিক পরিকল্পনা এবং সরকারি প্রকল্পের তথ্য এক জায়গায় পান।', start: 'ব্যবসার যাত্রা শুরু করুন', how: 'কীভাবে কাজ করে', local: 'স্থানীয় তথ্য', demand: 'দুগ্ধের চাহিদা • বেশি', explore: 'UdyamSetu দেখুন', exploreAction: 'দেখুন', insightsTitle: 'ব্যবসার তথ্য', insightsText: 'স্থানীয় বাজারের অবস্থা দেখুন', calculatorTitle: 'স্মার্ট ক্যালকুলেটর', calculatorText: 'প্রকল্প ও ঋণের কাঠামো হিসাব করুন', assistantTitle: 'AI সহায়ক', assistantText: 'সহজ ভাষায় প্রশ্ন করুন', schemesTitle: 'সরকারি প্রকল্প', schemesText: 'প্রকল্পের নিয়ম ও সীমা দেখুন' } },
  mr: { nav: { home: 'मुख्यपृष्ठ', how: 'हे कसे कार्य करते', schemes: 'योजना', insights: 'व्यवसाय माहिती', calculator: 'कॅल्क्युलेटर', assistant: 'AI सहाय्यक', getStarted: 'सुरुवात करा', language: 'भाषा' }, home: { kicker: 'ग्रामीण भारतासाठी AI व्यवसाय सल्ला', titleLead: 'तुमचा', titleHighlight: 'योग्य व्यवसाय साथी', description: 'योग्य मार्गदर्शनासह योग्य व्यवसाय सुरू करा. स्थानिक बाजार, आर्थिक नियोजन आणि सरकारी योजनांची माहिती एका ठिकाणी मिळवा.', start: 'व्यवसाय प्रवास सुरू करा', how: 'हे कसे कार्य करते', local: 'स्थानिक माहिती', demand: 'दुग्ध व्यवसायाची मागणी • जास्त', explore: 'UdyamSetu पाहा', exploreAction: 'पाहा', insightsTitle: 'व्यवसाय माहिती', insightsText: 'स्थानिक बाजाराची माहिती पाहा', calculatorTitle: 'स्मार्ट कॅल्क्युलेटर', calculatorText: 'प्रकल्प आणि कर्ज रचनेचा अंदाज घ्या', assistantTitle: 'AI सहाय्यक', assistantText: 'सोप्या भाषेत प्रश्न विचारा', schemesTitle: 'सरकारी योजना', schemesText: 'योजनेचे नियम आणि मर्यादा पाहा' } },
  ta: { nav: { home: 'முகப்பு', how: 'எப்படி செயல்படுகிறது', schemes: 'திட்டங்கள்', insights: 'வணிக தகவல்', calculator: 'கணிப்பான்', assistant: 'AI உதவியாளர்', getStarted: 'தொடங்குங்கள்', language: 'மொழி' }, home: { kicker: 'கிராமப்புற இந்தியாவுக்கான AI வணிக ஆலோசனை', titleLead: 'உங்கள்', titleHighlight: 'சரியான வணிகத் துணை', description: 'சரியான வழிகாட்டுதலுடன் சரியான தொழிலைத் தொடங்குங்கள். உள்ளூர் சந்தை, நிதித் திட்டம் மற்றும் அரசு திட்டத் தகவல்களை ஒரே இடத்தில் பெறுங்கள்.', start: 'வணிகப் பயணத்தைத் தொடங்குங்கள்', how: 'எப்படி செயல்படுகிறது', local: 'உள்ளூர் தகவல்', demand: 'பால் பொருட்களுக்கான தேவை • அதிகம்', explore: 'UdyamSetu ஐப் பாருங்கள்', exploreAction: 'பாருங்கள்', insightsTitle: 'வணிக தகவல்', insightsText: 'உள்ளூர் சந்தை நிலையைப் பாருங்கள்', calculatorTitle: 'ஸ்மார்ட் கணிப்பான்', calculatorText: 'திட்டம் மற்றும் கடன் அமைப்பை மதிப்பிடுங்கள்', assistantTitle: 'AI உதவியாளர்', assistantText: 'எளிய மொழியில் கேள்விகள் கேளுங்கள்', schemesTitle: 'அரசுத் திட்டங்கள்', schemesText: 'திட்ட விதிகள் மற்றும் வரம்புகளைப் பாருங்கள்' } },
  te: { nav: { home: 'హోమ్', how: 'ఇది ఎలా పనిచేస్తుంది', schemes: 'పథకాలు', insights: 'వ్యాపార సమాచారం', calculator: 'కాలిక్యులేటర్', assistant: 'AI సహాయకుడు', getStarted: 'ప్రారంభించండి', language: 'భాష' }, home: { kicker: 'గ్రామీణ భారతదేశం కోసం AI వ్యాపార సలహా', titleLead: 'మీ', titleHighlight: 'సరైన వ్యాపార సహచరుడు', description: 'సరైన మార్గదర్శకత్వంతో సరైన వ్యాపారాన్ని ప్రారంభించండి. స్థానిక మార్కెట్, ఆర్థిక ప్రణాళిక మరియు ప్రభుత్వ పథకాల సమాచారాన్ని ఒకే చోట పొందండి.', start: 'మీ వ్యాపార ప్రయాణాన్ని ప్రారంభించండి', how: 'ఇది ఎలా పనిచేస్తుంది', local: 'స్థానిక సమాచారం', demand: 'పాల ఉత్పత్తుల డిమాండ్ • ఎక్కువ', explore: 'UdyamSetu చూడండి', exploreAction: 'చూడండి', insightsTitle: 'వ్యాపార సమాచారం', insightsText: 'స్థానిక మార్కెట్ పరిస్థితులను చూడండి', calculatorTitle: 'స్మార్ట్ కాలిక్యులేటర్', calculatorText: 'ప్రాజెక్ట్ మరియు రుణ నిర్మాణాన్ని అంచనా వేయండి', assistantTitle: 'AI సహాయకుడు', assistantText: 'సులభమైన భాషలో ప్రశ్నలు అడగండి', schemesTitle: 'ప్రభుత్వ పథకాలు', schemesText: 'పథకం నియమాలు మరియు పరిమితులను చూడండి' } },
  kn: { nav: { home: 'ಮುಖಪುಟ', how: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', schemes: 'ಯೋಜನೆಗಳು', insights: 'ವ್ಯಾಪಾರ ಮಾಹಿತಿ', calculator: 'ಕ್ಯಾಲ್ಕುಲೇಟರ್', assistant: 'AI ಸಹಾಯಕ', getStarted: 'ಪ್ರಾರಂಭಿಸಿ', language: 'ಭಾಷೆ' }, home: { kicker: 'ಗ್ರಾಮೀಣ ಭಾರತಕ್ಕಾಗಿ AI ವ್ಯಾಪಾರ ಸಲಹೆ', titleLead: 'ನಿಮ್ಮ', titleHighlight: 'ಸರಿಯಾದ ವ್ಯಾಪಾರ ಸಂಗಾತಿ', description: 'ಸರಿಯಾದ ಮಾರ್ಗದರ್ಶನದೊಂದಿಗೆ ಸರಿಯಾದ ವ್ಯಾಪಾರವನ್ನು ಪ್ರಾರಂಭಿಸಿ. ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ, ಹಣಕಾಸು ಯೋಜನೆ ಮತ್ತು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಮಾಹಿತಿಯನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಪಡೆಯಿರಿ.', start: 'ನಿಮ್ಮ ವ್ಯಾಪಾರ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ', how: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', local: 'ಸ್ಥಳೀಯ ಮಾಹಿತಿ', demand: 'ಹಾಲು ಉತ್ಪನ್ನಗಳ ಬೇಡಿಕೆ • ಹೆಚ್ಚು', explore: 'UdyamSetu ನೋಡಿ', exploreAction: 'ನೋಡಿ', insightsTitle: 'ವ್ಯಾಪಾರ ಮಾಹಿತಿ', insightsText: 'ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ ಪರಿಸ್ಥಿತಿ ನೋಡಿ', calculatorTitle: 'ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್', calculatorText: 'ಯೋಜನೆ ಮತ್ತು ಸಾಲದ ರಚನೆ ಅಂದಾಜಿಸಿ', assistantTitle: 'AI ಸಹಾಯಕ', assistantText: 'ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಪ್ರಶ್ನೆ ಕೇಳಿ', schemesTitle: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', schemesText: 'ಯೋಜನೆಯ ನಿಯಮ ಮತ್ತು ಮಿತಿಗಳನ್ನು ನೋಡಿ' } },
  gu: { nav: { home: 'હોમ', how: 'આ કેવી રીતે કામ કરે છે', schemes: 'યોજનાઓ', insights: 'વ્યવસાય માહિતી', calculator: 'કેલ્ક્યુલેટર', assistant: 'AI સહાયક', getStarted: 'શરૂ કરો', language: 'ભાષા' }, home: { kicker: 'ગ્રામીણ ભારત માટે AI વ્યવસાય સલાહ', titleLead: 'તમારો', titleHighlight: 'સાચો વ્યવસાય સાથી', description: 'યોગ્ય માર્ગદર્શન સાથે યોગ્ય વ્યવસાય શરૂ કરો. સ્થાનિક બજાર, નાણાકીય આયોજન અને સરકારી યોજનાઓની માહિતી એક જ સ્થળે મેળવો.', start: 'તમારી વ્યવસાય યાત્રા શરૂ કરો', how: 'આ કેવી રીતે કામ કરે છે', local: 'સ્થાનિક માહિતી', demand: 'ડેરીની માંગ • વધુ', explore: 'UdyamSetu જુઓ', exploreAction: 'જુઓ', insightsTitle: 'વ્યવસાય માહિતી', insightsText: 'સ્થાનિક બજારની સ્થિતિ જુઓ', calculatorTitle: 'સ્માર્ટ કેલ્ક્યુલેટર', calculatorText: 'પ્રોજેક્ટ અને લોનની રચનાનો અંદાજ લો', assistantTitle: 'AI સહાયક', assistantText: 'સરળ ભાષામાં પ્રશ્નો પૂછો', schemesTitle: 'સરકારી યોજનાઓ', schemesText: 'યોજનાના નિયમો અને મર્યાદાઓ જુઓ' } },
  pa: { nav: { home: 'ਹੋਮ', how: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', schemes: 'ਯੋਜਨਾਵਾਂ', insights: 'ਕਾਰੋਬਾਰੀ ਜਾਣਕਾਰੀ', calculator: 'ਕੈਲਕੁਲੇਟਰ', assistant: 'AI ਸਹਾਇਕ', getStarted: 'ਸ਼ੁਰੂ ਕਰੋ', language: 'ਭਾਸ਼ਾ' }, home: { kicker: 'ਪੇਂਡੂ ਭਾਰਤ ਲਈ AI ਕਾਰੋਬਾਰੀ ਸਲਾਹ', titleLead: 'ਤੁਹਾਡਾ', titleHighlight: 'ਸਹੀ ਕਾਰੋਬਾਰੀ ਸਾਥੀ', description: 'ਸਹੀ ਮਾਰਗਦਰਸ਼ਨ ਨਾਲ ਸਹੀ ਕਾਰੋਬਾਰ ਸ਼ੁਰੂ ਕਰੋ। ਸਥਾਨਕ ਬਾਜ਼ਾਰ, ਵਿੱਤੀ ਯੋਜਨਾ ਅਤੇ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਦੀ ਜਾਣਕਾਰੀ ਇੱਕ ਥਾਂ ਲਵੋ।', start: 'ਆਪਣੀ ਕਾਰੋਬਾਰੀ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ', how: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', local: 'ਸਥਾਨਕ ਜਾਣਕਾਰੀ', demand: 'ਡੇਅਰੀ ਦੀ ਮੰਗ • ਵੱਧ', explore: 'UdyamSetu ਵੇਖੋ', exploreAction: 'ਵੇਖੋ', insightsTitle: 'ਕਾਰੋਬਾਰੀ ਜਾਣਕਾਰੀ', insightsText: 'ਸਥਾਨਕ ਬਾਜ਼ਾਰ ਦੀ ਸਥਿਤੀ ਵੇਖੋ', calculatorTitle: 'ਸਮਾਰਟ ਕੈਲਕੁਲੇਟਰ', calculatorText: 'ਪ੍ਰੋਜੈਕਟ ਅਤੇ ਕਰਜ਼ੇ ਦੀ ਬਣਤਰ ਦਾ ਅੰਦਾਜ਼ਾ ਲਵੋ', assistantTitle: 'AI ਸਹਾਇਕ', assistantText: 'ਸੌਖੀ ਭਾਸ਼ਾ ਵਿੱਚ ਸਵਾਲ ਪੁੱਛੋ', schemesTitle: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ', schemesText: 'ਯੋਜਨਾ ਦੇ ਨਿਯਮ ਅਤੇ ਹੱਦਾਂ ਵੇਖੋ' } },
  ml: { nav: { home: 'ഹോം', how: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു', schemes: 'പദ്ധതികൾ', insights: 'ബിസിനസ് വിവരങ്ങൾ', calculator: 'കാൽക്കുലേറ്റർ', assistant: 'AI സഹായി', getStarted: 'ആരംഭിക്കുക', language: 'ഭാഷ' }, home: { kicker: 'ഗ്രാമീണ ഇന്ത്യയ്ക്കുള്ള AI ബിസിനസ് ഉപദേശം', titleLead: 'നിങ്ങളുടെ', titleHighlight: 'ശരിയായ ബിസിനസ് കൂട്ടുകാരൻ', description: 'ശരിയായ മാർഗനിർദേശത്തോടെ ശരിയായ ബിസിനസ് ആരംഭിക്കുക. പ്രാദേശിക വിപണി, സാമ്പത്തിക ആസൂത്രണം, സർക്കാർ പദ്ധതികൾ എന്നിവയുടെ വിവരങ്ങൾ ഒരിടത്ത് നേടുക.', start: 'ബിസിനസ് യാത്ര ആരംഭിക്കുക', how: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു', local: 'പ്രാദേശിക വിവരം', demand: 'ഡയറി ആവശ്യകത • ഉയർന്നത്', explore: 'UdyamSetu കാണുക', exploreAction: 'കാണുക', insightsTitle: 'ബിസിനസ് വിവരങ്ങൾ', insightsText: 'പ്രാദേശിക വിപണി നില കാണുക', calculatorTitle: 'സ്മാർട്ട് കാൽക്കുലേറ്റർ', calculatorText: 'പദ്ധതിയും വായ്പാ ഘടനയും കണക്കാക്കുക', assistantTitle: 'AI സഹായി', assistantText: 'ലളിതമായ ഭാഷയിൽ ചോദ്യങ്ങൾ ചോദിക്കുക', schemesTitle: 'സർക്കാർ പദ്ധതികൾ', schemesText: 'പദ്ധതി നിയമങ്ങളും പരിധികളും കാണുക' } },
  or: { nav: { home: 'ମୁଖ୍ୟପୃଷ୍ଠା', how: 'ଏହା କିପରି କାମ କରେ', schemes: 'ଯୋଜନା', insights: 'ବ୍ୟବସାୟ ସୂଚନା', calculator: 'କ୍ୟାଲକୁଲେଟର', assistant: 'AI ସହାୟକ', getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ', language: 'ଭାଷା' }, home: { kicker: 'ଗ୍ରାମୀଣ ଭାରତ ପାଇଁ AI ବ୍ୟବସାୟ ପରାମର୍ଶ', titleLead: 'ଆପଣଙ୍କ', titleHighlight: 'ସଠିକ ବ୍ୟବସାୟ ସାଥୀ', description: 'ସଠିକ ମାର୍ଗଦର୍ଶନ ସହିତ ସଠିକ ବ୍ୟବସାୟ ଆରମ୍ଭ କରନ୍ତୁ। ସ୍ଥାନୀୟ ବଜାର, ଆର୍ଥିକ ଯୋଜନା ଏବଂ ସରକାରୀ ଯୋଜନାର ସୂଚନା ଗୋଟିଏ ସ୍ଥାନରେ ପାଆନ୍ତୁ।', start: 'ଆପଣଙ୍କ ବ୍ୟବସାୟ ଯାତ୍ରା ଆରମ୍ଭ କରନ୍ତୁ', how: 'ଏହା କିପରି କାମ କରେ', local: 'ସ୍ଥାନୀୟ ସୂଚନା', demand: 'ଦୁଗ୍ଧ ଚାହିଦା • ଅଧିକ', explore: 'UdyamSetu ଦେଖନ୍ତୁ', exploreAction: 'ଦେଖନ୍ତୁ', insightsTitle: 'ବ୍ୟବସାୟ ସୂଚନା', insightsText: 'ସ୍ଥାନୀୟ ବଜାର ସ୍ଥିତି ଦେଖନ୍ତୁ', calculatorTitle: 'ସ୍ମାର୍ଟ କ୍ୟାଲକୁଲେଟର', calculatorText: 'ପ୍ରକଳ୍ପ ଏବଂ ଋଣ ଗଠନର ଅନୁମାନ କରନ୍ତୁ', assistantTitle: 'AI ସହାୟକ', assistantText: 'ସରଳ ଭାଷାରେ ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ', schemesTitle: 'ସରକାରୀ ଯୋଜନା', schemesText: 'ଯୋଜନା ନିୟମ ଏବଂ ସୀମା ଦେଖନ୍ତୁ' } },
}

const pageTranslations = {
  en: {
    common: { online: 'Online', perAnnum: 'per annum', maximum: 'maximum', beforeRepayment: 'before repayment', whoApply: 'Who can apply?', example: 'Example', menu: 'Menu' },
    how: { kicker: 'Simple guided journey', title: 'How UdyamSetu Works?', subtitle: 'A simple 4-step journey from idea to successful enterprise.', step1Title: 'Share Your Details', step1Text: 'Tell us your location, available margin money and business idea.', step2Title: 'Get Local Insights', step2Text: 'Our AI analyzes market demand, competition and opportunities in your area.', step3Title: 'See Financial Plan', step3Text: 'Know total project cost, loan eligibility, EMI and scheme details instantly.', step4Title: 'Start with Confidence', step4Text: 'Take an informed decision and build a profitable, sustainable business.', impact: 'Empowering Rural India. One Successful Entrepreneur at a Time.', rural: 'Rural Entrepreneurs', categories: 'Business Categories', villages: 'Villages Covered', satisfaction: 'User Satisfaction' },
    schemes: { title: 'Government Schemes for You', subtitle: 'We match your project with the best suitable financing structure.', loanAmount: 'Loan Amount', interestRate: 'Interest Rate', noticeTitle: 'Not sure which scheme is right for you?', noticeText: 'Use the Smart Calculator to estimate your project cost and see the recommended route.', question: 'Want to know which scheme fits your project?', questionText: 'Use the calculator to route your indicative project cost automatically.', try: 'Try Calculator' },
    calculator: { title: 'Financial Calculator', subtitle: 'Calculate your project cost, loan amount and repayment details.', details: 'Enter Your Details', margin: 'Available Margin Money (₹)', category: 'Business Category', location: 'Location', calculate: 'Calculate Now', theoretical: 'Theoretical Project Cost', theoreticalHelp: 'Based on 10% margin', eligible: 'Eligible Project Cost', eligibleWithin: 'Within scheme limit', eligibleCapped: 'Limited by scheme cap', maxLoan: 'Maximum Loan Amount', own: 'Required Own Contribution', sufficient: 'Available margin is sufficient', additional: 'additional needed', recommended: 'Recommended Scheme', assumptions: 'Planning assumptions', assumptionsText: 'This estimate uses the stated margin ratio, scheme limits, and standard EMI formula. Confirm current terms and eligibility with the authorized agency.', capped: 'Your theoretical project cost exceeds the supported structure. The eligible project cost is capped at', additionalPath: 'or an alternative financing path may be needed.', repayment: 'Repayment Plan (Indicative)', repaymentText: 'Monthly EMI shown for planning only. Moratorium treatment may differ under official rules.', interest: 'Interest Rate', tenure: 'Repayment Tenure', moratorium: 'Moratorium Period', payment: 'Estimated payment (After Moratorium)', monthly: 'Monthly', quarterly: 'Quarterly', month: 'Month', quarter: 'Quarter', moratoriumText: 'Interest during the moratorium is subject to official scheme treatment.' },
    insights: { title: 'Business Insights', subtitle: 'Explore business opportunities near your selected location.', get: 'Get Insights', state: 'State', district: 'District', block: 'Block', category: 'Category', population: 'Population (10km radius)', households: 'Estimated Households', income: 'Avg. Monthly Income', potential: 'Market Potential', estimate: 'Model estimate', opportunity: 'Demand & Opportunity', competition: 'Competition Snapshot', existing: 'Existing businesses', level: 'Competition level', saturation: 'Market Saturation', key: 'Key Insights', prototype: 'These are prototype insights and should be replaced with sourced local data.', readiness: 'Report readiness', advisory: 'Advisory estimate', download: 'Download summary', ask: 'Ask about this result' },
    homeExtra: { feature1Title: 'Hyper Local Market Analysis', feature1Text: 'Know what business works in your location', feature2Title: 'Smart Loan & Scheme Guide', feature2Text: 'Find the right scheme, amount and repayment plan', feature3Title: 'AI Business Assistant', feature3Text: 'Get answers in your own language, anytime', feature4Title: 'Business Feasibility Report', feature4Text: 'Detailed strategy before you invest your money' },
    assistant: { title: 'AI Business Assistant', subtitle: 'Ask anything about business, loans or schemes in your language.', popular: 'Popular Questions', placeholder: 'Type your message...', name: 'UdyamSetu Assistant', description: 'I can explain schemes, calculate indicative loan structures, discuss market opportunities, and answer questions in simple language.', talk: 'Talk to Assistant' },
    footer: { tagline: 'AI-driven rural business advisory', description: 'Hyper-local market intelligence, transparent financial rules and multilingual assistance for first-time entrepreneurs.', explore: 'Explore', how: 'How it works', schemes: 'Government schemes', insights: 'Business insights', important: 'Important', disclaimer: 'Calculations shown in this prototype are indicative estimates. Official eligibility, appraisal and approval always depend on the authorized agency.' },
  },
  hi: {
    common: { online: 'ऑनलाइन', perAnnum: 'प्रति वर्ष', maximum: 'अधिकतम', beforeRepayment: 'भुगतान से पहले', whoApply: 'कौन आवेदन कर सकता है?', example: 'उदाहरण', menu: 'मेन्यू' },
    how: { kicker: 'सरल मार्गदर्शित यात्रा', title: 'UdyamSetu कैसे काम करता है?', subtitle: 'विचार से सफल उद्यम तक 4 आसान चरण।', step1Title: 'अपनी जानकारी दें', step1Text: 'अपना स्थान, उपलब्ध मार्जिन राशि और व्यवसाय का विचार बताएं।', step2Title: 'स्थानीय जानकारी पाएं', step2Text: 'AI आपके क्षेत्र की मांग, प्रतिस्पर्धा और अवसरों का विश्लेषण करता है।', step3Title: 'वित्तीय योजना देखें', step3Text: 'परियोजना लागत, ऋण पात्रता, EMI और योजना की जानकारी तुरंत पाएं।', step4Title: 'विश्वास के साथ शुरू करें', step4Text: 'जानकारी के आधार पर निर्णय लें और टिकाऊ व्यवसाय बनाएं।', impact: 'ग्रामीण भारत को सशक्त बनाना। एक समय में एक सफल उद्यमी।', rural: 'ग्रामीण उद्यमी', categories: 'व्यवसाय श्रेणियां', villages: 'कवर किए गए गांव', satisfaction: 'उपयोगकर्ता संतुष्टि' },
    schemes: { title: 'आपके लिए सरकारी योजनाएं', subtitle: 'हम आपकी परियोजना के लिए उपयुक्त वित्तीय संरचना बताते हैं।', loanAmount: 'ऋण राशि', interestRate: 'ब्याज दर', noticeTitle: 'कौन सी योजना सही है, पता नहीं?', noticeText: 'परियोजना लागत का अनुमान लगाने और सही मार्ग देखने के लिए स्मार्ट कैलकुलेटर का उपयोग करें।', question: 'जानना चाहते हैं कि कौन सी योजना आपकी परियोजना के लिए सही है?', questionText: 'अपनी अनुमानित परियोजना लागत को सही योजना से जोड़ने के लिए कैलकुलेटर का उपयोग करें।', try: 'कैलकुलेटर आजमाएं' },
    calculator: { title: 'वित्तीय कैलकुलेटर', subtitle: 'अपनी परियोजना लागत, ऋण राशि और भुगतान विवरण की गणना करें।', details: 'अपनी जानकारी दें', margin: 'उपलब्ध मार्जिन राशि (₹)', category: 'व्यवसाय श्रेणी', location: 'स्थान', calculate: 'अभी गणना करें', theoretical: 'सैद्धांतिक परियोजना लागत', theoreticalHelp: '10% मार्जिन के आधार पर', eligible: 'पात्र परियोजना लागत', eligibleWithin: 'योजना सीमा के भीतर', eligibleCapped: 'योजना सीमा से सीमित', maxLoan: 'अधिकतम ऋण राशि', own: 'आवश्यक अपनी पूंजी', sufficient: 'उपलब्ध मार्जिन पर्याप्त है', additional: 'अतिरिक्त आवश्यक', recommended: 'अनुशंसित योजना', assumptions: 'योजना संबंधी मान्यताएं', assumptionsText: 'यह अनुमान मार्जिन अनुपात, योजना सीमा और EMI सूत्र पर आधारित है। वर्तमान शर्तों और पात्रता की अधिकृत एजेंसी से पुष्टि करें।', capped: 'आपकी सैद्धांतिक परियोजना लागत समर्थित संरचना से अधिक है। पात्र परियोजना लागत की सीमा', additionalPath: 'या वैकल्पिक वित्तीय मार्ग की आवश्यकता हो सकती है।', repayment: 'भुगतान योजना (अनुमानित)', repaymentText: 'मासिक EMI केवल योजना के लिए है। अधिस्थगन का व्यवहार आधिकारिक नियमों से अलग हो सकता है।', interest: 'ब्याज दर', tenure: 'भुगतान अवधि', moratorium: 'अधिस्थगन अवधि', payment: 'अनुमानित भुगतान (अधिस्थगन के बाद)', monthly: 'मासिक', quarterly: 'त्रैमासिक', month: 'महीना', quarter: 'तिमाही', moratoriumText: 'अधिस्थगन अवधि का ब्याज आधिकारिक योजना नियमों पर निर्भर है।' },
    insights: { title: 'व्यवसाय जानकारी', subtitle: 'चुने गए स्थान के पास व्यवसाय के अवसर देखें।', get: 'जानकारी पाएं', state: 'राज्य', district: 'जिला', block: 'ब्लॉक', category: 'श्रेणी', population: 'जनसंख्या (10 किमी क्षेत्र)', households: 'अनुमानित परिवार', income: 'औसत मासिक आय', potential: 'बाजार क्षमता', estimate: 'मॉडल अनुमान', opportunity: 'मांग और अवसर', competition: 'प्रतिस्पर्धा का अवलोकन', existing: 'मौजूदा व्यवसाय', level: 'प्रतिस्पर्धा स्तर', saturation: 'बाजार संतृप्ति', key: 'मुख्य जानकारी', prototype: 'ये प्रोटोटाइप जानकारी हैं और इन्हें स्रोत आधारित स्थानीय डेटा से बदलना चाहिए।', readiness: 'रिपोर्ट तैयार', advisory: 'सलाहकार अनुमान', download: 'सारांश डाउनलोड करें', ask: 'इस परिणाम के बारे में पूछें' },
    homeExtra: { feature1Title: 'स्थानीय बाजार विश्लेषण', feature1Text: 'जानें कि आपके स्थान पर कौन सा व्यवसाय चलेगा', feature2Title: 'स्मार्ट ऋण और योजना मार्गदर्शक', feature2Text: 'सही योजना, राशि और भुगतान योजना पाएं', feature3Title: 'AI व्यवसाय सहायक', feature3Text: 'कभी भी अपनी भाषा में उत्तर पाएं', feature4Title: 'व्यवसाय व्यवहार्यता रिपोर्ट', feature4Text: 'पैसा लगाने से पहले विस्तृत रणनीति पाएं' },
    assistant: { title: 'AI व्यवसाय सहायक', subtitle: 'व्यवसाय, ऋण या योजनाओं के बारे में अपनी भाषा में पूछें।', popular: 'लोकप्रिय प्रश्न', placeholder: 'अपना संदेश लिखें...', name: 'UdyamSetu सहायक', description: 'मैं योजनाओं को समझा सकता हूं, अनुमानित ऋण संरचना की गणना कर सकता हूं और बाजार के अवसरों पर सरल भाषा में जवाब दे सकता हूं।', talk: 'सहायक से बात करें' },
    footer: { tagline: 'AI आधारित ग्रामीण व्यवसाय सलाह', description: 'पहली बार उद्यम शुरू करने वालों के लिए स्थानीय बाजार जानकारी, पारदर्शी वित्तीय नियम और बहुभाषी सहायता।', explore: 'देखें', how: 'यह कैसे काम करता है', schemes: 'सरकारी योजनाएं', insights: 'व्यवसाय जानकारी', important: 'महत्वपूर्ण', disclaimer: 'इस प्रोटोटाइप में दिखाई गई गणनाएं अनुमानित हैं। आधिकारिक पात्रता और मंजूरी अधिकृत एजेंसी पर निर्भर करती है।' },
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => window.localStorage.getItem('udyamsetu-language') || 'en')

  useEffect(() => {
    window.localStorage.setItem('udyamsetu-language', language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo(() => {
    const selected = { ...translations.en, ...translations[language], ...pageTranslations.en, ...pageTranslations[language] }
    return {
      language,
      setLanguage: setLanguageState,
      languageLabel: languages.find((item) => item.code === language)?.label ?? 'English',
      t: (section, key) => selected[section]?.[key] ?? key,
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}